name:                expense-tracker
version:             0.2.0.0
github:              "wgaffa/expense-tracker"
license:             BSD3
author:              "Patrik Maunus"
maintainer:          "subscription@skriptladan.se"
copyright:           "2020 Patrik Maunus"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/expense-tracker#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- time
- uuid

library:
  source-dirs: src

executables:
  dee-book:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - expense-tracker
    - mtl
    - optparse-applicative
    - repline
    - transformers
    - sqlite-simple
    - exceptions
    - boxes
    - gitrev
    - free

tests:
  expense-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expense-tracker
